name: Django App CI/CD

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-test:
    name: Build and Test Django App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker environment
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.dev
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.dev
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.dev
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env.dev
          echo "DB_ENGINE=${{ secrets.DB_ENGINE }}" >> .env.dev
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env.dev
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env.dev
          echo "DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }}" >> .env.dev
          echo "DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}" >> .env.dev
          echo "DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}" >> .env.dev
          echo "DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}" >> .env.dev

      - name: Build Docker Container
        run: docker-compose --env-file .env.dev -f docker-compose.dev.yml up -d

      - name: Run Tests
        run: docker-compose exec -T djangoapp python manage.py test

      - name: Cleanup
        run: docker-compose --env-file .env.dev -f docker-compose.dev.yml down
